# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import api_gateway_pb2 as api__gateway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApiGatewayStub(object):
    """============================================================
    API Gateway - единая точка входа для всех сервисов Director
    ============================================================

    === Подключение и статус ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/api_gateway.ApiGateway/HealthCheck',
                request_serializer=api__gateway__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetServicesInfo = channel.unary_unary(
                '/api_gateway.ApiGateway/GetServicesInfo',
                request_serializer=api__gateway__pb2.GetServicesInfoRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.GetServicesInfoResponse.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/api_gateway.ApiGateway/ListProjects',
                request_serializer=api__gateway__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/api_gateway.ApiGateway/CreateProject',
                request_serializer=api__gateway__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.OpenProject = channel.unary_unary(
                '/api_gateway.ApiGateway/OpenProject',
                request_serializer=api__gateway__pb2.OpenProjectRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.OpenProjectResponse.FromString,
                _registered_method=True)
        self.DeleteProject = channel.unary_unary(
                '/api_gateway.ApiGateway/DeleteProject',
                request_serializer=api__gateway__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.DeleteProjectResponse.FromString,
                _registered_method=True)
        self.GetStorageInfo = channel.unary_unary(
                '/api_gateway.ApiGateway/GetStorageInfo',
                request_serializer=api__gateway__pb2.GetStorageInfoRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.GetStorageInfoResponse.FromString,
                _registered_method=True)
        self.BrowseDirectory = channel.unary_unary(
                '/api_gateway.ApiGateway/BrowseDirectory',
                request_serializer=api__gateway__pb2.BrowseDirectoryRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.BrowseDirectoryResponse.FromString,
                _registered_method=True)
        self.CreateDirectory = channel.unary_unary(
                '/api_gateway.ApiGateway/CreateDirectory',
                request_serializer=api__gateway__pb2.CreateDirectoryRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.CreateDirectoryResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/api_gateway.ApiGateway/Delete',
                request_serializer=api__gateway__pb2.DeleteRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.InitProjectStructure = channel.unary_unary(
                '/api_gateway.ApiGateway/InitProjectStructure',
                request_serializer=api__gateway__pb2.InitProjectStructureRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.InitProjectStructureResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/api_gateway.ApiGateway/UploadFile',
                request_serializer=api__gateway__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/api_gateway.ApiGateway/DownloadFile',
                request_serializer=api__gateway__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=api__gateway__pb2.DownloadFileResponse.FromString,
                _registered_method=True)


class ApiGatewayServicer(object):
    """============================================================
    API Gateway - единая точка входа для всех сервисов Director
    ============================================================

    === Подключение и статус ===
    """

    def HealthCheck(self, request, context):
        """Проверить состояние всех сервисов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServicesInfo(self, request, context):
        """Получить информацию о всех подключённых сервисах
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """=== Проекты (проксирование к DirectorEngine) ===

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorageInfo(self, request, context):
        """=== Файловая система (проксирование к FileGateway) ===

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowseDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitProjectStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Стриминг файлов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=api__gateway__pb2.HealthCheckRequest.FromString,
                    response_serializer=api__gateway__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetServicesInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServicesInfo,
                    request_deserializer=api__gateway__pb2.GetServicesInfoRequest.FromString,
                    response_serializer=api__gateway__pb2.GetServicesInfoResponse.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=api__gateway__pb2.ListProjectsRequest.FromString,
                    response_serializer=api__gateway__pb2.ListProjectsResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=api__gateway__pb2.CreateProjectRequest.FromString,
                    response_serializer=api__gateway__pb2.CreateProjectResponse.SerializeToString,
            ),
            'OpenProject': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenProject,
                    request_deserializer=api__gateway__pb2.OpenProjectRequest.FromString,
                    response_serializer=api__gateway__pb2.OpenProjectResponse.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=api__gateway__pb2.DeleteProjectRequest.FromString,
                    response_serializer=api__gateway__pb2.DeleteProjectResponse.SerializeToString,
            ),
            'GetStorageInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorageInfo,
                    request_deserializer=api__gateway__pb2.GetStorageInfoRequest.FromString,
                    response_serializer=api__gateway__pb2.GetStorageInfoResponse.SerializeToString,
            ),
            'BrowseDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowseDirectory,
                    request_deserializer=api__gateway__pb2.BrowseDirectoryRequest.FromString,
                    response_serializer=api__gateway__pb2.BrowseDirectoryResponse.SerializeToString,
            ),
            'CreateDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDirectory,
                    request_deserializer=api__gateway__pb2.CreateDirectoryRequest.FromString,
                    response_serializer=api__gateway__pb2.CreateDirectoryResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=api__gateway__pb2.DeleteRequest.FromString,
                    response_serializer=api__gateway__pb2.DeleteResponse.SerializeToString,
            ),
            'InitProjectStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.InitProjectStructure,
                    request_deserializer=api__gateway__pb2.InitProjectStructureRequest.FromString,
                    response_serializer=api__gateway__pb2.InitProjectStructureResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=api__gateway__pb2.UploadFileRequest.FromString,
                    response_serializer=api__gateway__pb2.UploadFileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=api__gateway__pb2.DownloadFileRequest.FromString,
                    response_serializer=api__gateway__pb2.DownloadFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api_gateway.ApiGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api_gateway.ApiGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApiGateway(object):
    """============================================================
    API Gateway - единая точка входа для всех сервисов Director
    ============================================================

    === Подключение и статус ===
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/HealthCheck',
            api__gateway__pb2.HealthCheckRequest.SerializeToString,
            api__gateway__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServicesInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetServicesInfo',
            api__gateway__pb2.GetServicesInfoRequest.SerializeToString,
            api__gateway__pb2.GetServicesInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/ListProjects',
            api__gateway__pb2.ListProjectsRequest.SerializeToString,
            api__gateway__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/CreateProject',
            api__gateway__pb2.CreateProjectRequest.SerializeToString,
            api__gateway__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/OpenProject',
            api__gateway__pb2.OpenProjectRequest.SerializeToString,
            api__gateway__pb2.OpenProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/DeleteProject',
            api__gateway__pb2.DeleteProjectRequest.SerializeToString,
            api__gateway__pb2.DeleteProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStorageInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/GetStorageInfo',
            api__gateway__pb2.GetStorageInfoRequest.SerializeToString,
            api__gateway__pb2.GetStorageInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowseDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/BrowseDirectory',
            api__gateway__pb2.BrowseDirectoryRequest.SerializeToString,
            api__gateway__pb2.BrowseDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/CreateDirectory',
            api__gateway__pb2.CreateDirectoryRequest.SerializeToString,
            api__gateway__pb2.CreateDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/Delete',
            api__gateway__pb2.DeleteRequest.SerializeToString,
            api__gateway__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitProjectStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api_gateway.ApiGateway/InitProjectStructure',
            api__gateway__pb2.InitProjectStructureRequest.SerializeToString,
            api__gateway__pb2.InitProjectStructureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api_gateway.ApiGateway/UploadFile',
            api__gateway__pb2.UploadFileRequest.SerializeToString,
            api__gateway__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api_gateway.ApiGateway/DownloadFile',
            api__gateway__pb2.DownloadFileRequest.SerializeToString,
            api__gateway__pb2.DownloadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
