# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.api.proto import director_pb2 as director__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in director_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProjectServiceStub(object):
    """Сервис управления проектами и обработки видео
    Файловые операции перенесены в FileGateway
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProjects = channel.unary_unary(
                '/director.ProjectService/ListProjects',
                request_serializer=director__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=director__pb2.ListProjectsResponse.FromString,
                _registered_method=True)
        self.RegisterProject = channel.unary_unary(
                '/director.ProjectService/RegisterProject',
                request_serializer=director__pb2.RegisterProjectRequest.SerializeToString,
                response_deserializer=director__pb2.RegisterProjectResponse.FromString,
                _registered_method=True)
        self.OpenProject = channel.unary_unary(
                '/director.ProjectService/OpenProject',
                request_serializer=director__pb2.OpenProjectRequest.SerializeToString,
                response_deserializer=director__pb2.OpenProjectResponse.FromString,
                _registered_method=True)
        self.UnregisterProject = channel.unary_unary(
                '/director.ProjectService/UnregisterProject',
                request_serializer=director__pb2.UnregisterProjectRequest.SerializeToString,
                response_deserializer=director__pb2.UnregisterProjectResponse.FromString,
                _registered_method=True)
        self.GetEngineInfo = channel.unary_unary(
                '/director.ProjectService/GetEngineInfo',
                request_serializer=director__pb2.GetEngineInfoRequest.SerializeToString,
                response_deserializer=director__pb2.GetEngineInfoResponse.FromString,
                _registered_method=True)


class ProjectServiceServicer(object):
    """Сервис управления проектами и обработки видео
    Файловые операции перенесены в FileGateway
    """

    def ListProjects(self, request, context):
        """Получить список всех проектов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterProject(self, request, context):
        """Зарегистрировать новый проект (после создания структуры через FileGateway)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenProject(self, request, context):
        """Открыть существующий проект
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterProject(self, request, context):
        """Удалить проект из списка
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngineInfo(self, request, context):
        """Получить информацию о движке
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=director__pb2.ListProjectsRequest.FromString,
                    response_serializer=director__pb2.ListProjectsResponse.SerializeToString,
            ),
            'RegisterProject': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProject,
                    request_deserializer=director__pb2.RegisterProjectRequest.FromString,
                    response_serializer=director__pb2.RegisterProjectResponse.SerializeToString,
            ),
            'OpenProject': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenProject,
                    request_deserializer=director__pb2.OpenProjectRequest.FromString,
                    response_serializer=director__pb2.OpenProjectResponse.SerializeToString,
            ),
            'UnregisterProject': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterProject,
                    request_deserializer=director__pb2.UnregisterProjectRequest.FromString,
                    response_serializer=director__pb2.UnregisterProjectResponse.SerializeToString,
            ),
            'GetEngineInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngineInfo,
                    request_deserializer=director__pb2.GetEngineInfoRequest.FromString,
                    response_serializer=director__pb2.GetEngineInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'director.ProjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('director.ProjectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProjectService(object):
    """Сервис управления проектами и обработки видео
    Файловые операции перенесены в FileGateway
    """

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.ProjectService/ListProjects',
            director__pb2.ListProjectsRequest.SerializeToString,
            director__pb2.ListProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.ProjectService/RegisterProject',
            director__pb2.RegisterProjectRequest.SerializeToString,
            director__pb2.RegisterProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.ProjectService/OpenProject',
            director__pb2.OpenProjectRequest.SerializeToString,
            director__pb2.OpenProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.ProjectService/UnregisterProject',
            director__pb2.UnregisterProjectRequest.SerializeToString,
            director__pb2.UnregisterProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEngineInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/director.ProjectService/GetEngineInfo',
            director__pb2.GetEngineInfoRequest.SerializeToString,
            director__pb2.GetEngineInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
