# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: director.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'director.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64irector.proto\x12\x08\x64irector\"\x16\n\x14GetEngineInfoRequest\"V\n\x15GetEngineInfoResponse\x12\x11\n\tengine_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x19\n\x11supported_formats\x18\x03 \x03(\t\"w\n\x0bProjectInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x17\n\x0f\x66ile_gateway_id\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\x12\x13\n\x0bmodified_at\x18\x06 \x01(\x03\"\x15\n\x13ListProjectsRequest\"?\n\x14ListProjectsResponse\x12\'\n\x08projects\x18\x01 \x03(\x0b\x32\x15.director.ProjectInfo\"M\n\x16RegisterProjectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x17\n\x0f\x66ile_gateway_id\x18\x03 \x01(\t\"i\n\x17RegisterProjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12&\n\x07project\x18\x03 \x01(\x0b\x32\x15.director.ProjectInfo\"(\n\x12OpenProjectRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"e\n\x13OpenProjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12&\n\x07project\x18\x03 \x01(\x0b\x32\x15.director.ProjectInfo\".\n\x18UnregisterProjectRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\"C\n\x19UnregisterProjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xb3\x03\n\x0eProjectService\x12M\n\x0cListProjects\x12\x1d.director.ListProjectsRequest\x1a\x1e.director.ListProjectsResponse\x12V\n\x0fRegisterProject\x12 .director.RegisterProjectRequest\x1a!.director.RegisterProjectResponse\x12J\n\x0bOpenProject\x12\x1c.director.OpenProjectRequest\x1a\x1d.director.OpenProjectResponse\x12\\\n\x11UnregisterProject\x12\".director.UnregisterProjectRequest\x1a#.director.UnregisterProjectResponse\x12P\n\rGetEngineInfo\x12\x1e.director.GetEngineInfoRequest\x1a\x1f.director.GetEngineInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'director_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETENGINEINFOREQUEST']._serialized_start=28
  _globals['_GETENGINEINFOREQUEST']._serialized_end=50
  _globals['_GETENGINEINFORESPONSE']._serialized_start=52
  _globals['_GETENGINEINFORESPONSE']._serialized_end=138
  _globals['_PROJECTINFO']._serialized_start=140
  _globals['_PROJECTINFO']._serialized_end=259
  _globals['_LISTPROJECTSREQUEST']._serialized_start=261
  _globals['_LISTPROJECTSREQUEST']._serialized_end=282
  _globals['_LISTPROJECTSRESPONSE']._serialized_start=284
  _globals['_LISTPROJECTSRESPONSE']._serialized_end=347
  _globals['_REGISTERPROJECTREQUEST']._serialized_start=349
  _globals['_REGISTERPROJECTREQUEST']._serialized_end=426
  _globals['_REGISTERPROJECTRESPONSE']._serialized_start=428
  _globals['_REGISTERPROJECTRESPONSE']._serialized_end=533
  _globals['_OPENPROJECTREQUEST']._serialized_start=535
  _globals['_OPENPROJECTREQUEST']._serialized_end=575
  _globals['_OPENPROJECTRESPONSE']._serialized_start=577
  _globals['_OPENPROJECTRESPONSE']._serialized_end=678
  _globals['_UNREGISTERPROJECTREQUEST']._serialized_start=680
  _globals['_UNREGISTERPROJECTREQUEST']._serialized_end=726
  _globals['_UNREGISTERPROJECTRESPONSE']._serialized_start=728
  _globals['_UNREGISTERPROJECTRESPONSE']._serialized_end=795
  _globals['_PROJECTSERVICE']._serialized_start=798
  _globals['_PROJECTSERVICE']._serialized_end=1233
# @@protoc_insertion_point(module_scope)
