# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.api.proto import file_gateway_pb2 as file__gateway__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in file_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileGatewayStub(object):
    """Сервис управления файлами и хранилищем
    === Информация о сервере ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStorageInfo = channel.unary_unary(
                '/file_gateway.FileGateway/GetStorageInfo',
                request_serializer=file__gateway__pb2.GetStorageInfoRequest.SerializeToString,
                response_deserializer=file__gateway__pb2.GetStorageInfoResponse.FromString,
                _registered_method=True)
        self.BrowseDirectory = channel.unary_unary(
                '/file_gateway.FileGateway/BrowseDirectory',
                request_serializer=file__gateway__pb2.BrowseDirectoryRequest.SerializeToString,
                response_deserializer=file__gateway__pb2.BrowseDirectoryResponse.FromString,
                _registered_method=True)
        self.CreateDirectory = channel.unary_unary(
                '/file_gateway.FileGateway/CreateDirectory',
                request_serializer=file__gateway__pb2.CreateDirectoryRequest.SerializeToString,
                response_deserializer=file__gateway__pb2.CreateDirectoryResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/file_gateway.FileGateway/Delete',
                request_serializer=file__gateway__pb2.DeleteRequest.SerializeToString,
                response_deserializer=file__gateway__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.UploadFile = channel.stream_unary(
                '/file_gateway.FileGateway/UploadFile',
                request_serializer=file__gateway__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=file__gateway__pb2.UploadFileResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/file_gateway.FileGateway/DownloadFile',
                request_serializer=file__gateway__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=file__gateway__pb2.DownloadFileResponse.FromString,
                _registered_method=True)
        self.GetFileInfo = channel.unary_unary(
                '/file_gateway.FileGateway/GetFileInfo',
                request_serializer=file__gateway__pb2.GetFileInfoRequest.SerializeToString,
                response_deserializer=file__gateway__pb2.GetFileInfoResponse.FromString,
                _registered_method=True)
        self.InitProjectStructure = channel.unary_unary(
                '/file_gateway.FileGateway/InitProjectStructure',
                request_serializer=file__gateway__pb2.InitProjectStructureRequest.SerializeToString,
                response_deserializer=file__gateway__pb2.InitProjectStructureResponse.FromString,
                _registered_method=True)


class FileGatewayServicer(object):
    """Сервис управления файлами и хранилищем
    === Информация о сервере ===
    """

    def GetStorageInfo(self, request, context):
        """Получить информацию о файловом сервере
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowseDirectory(self, request, context):
        """=== Навигация по файловой системе ===

        Получить содержимое директории
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDirectory(self, request, context):
        """Создать директорию
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Удалить файл или директорию
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """=== Загрузка и скачивание файлов ===

        Загрузить файл на сервер (стриминг)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Скачать файл с сервера (стриминг)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileInfo(self, request, context):
        """Получить метаданные файла
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitProjectStructure(self, request, context):
        """=== Работа с проектами ===

        Инициализировать структуру проекта
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStorageInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorageInfo,
                    request_deserializer=file__gateway__pb2.GetStorageInfoRequest.FromString,
                    response_serializer=file__gateway__pb2.GetStorageInfoResponse.SerializeToString,
            ),
            'BrowseDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowseDirectory,
                    request_deserializer=file__gateway__pb2.BrowseDirectoryRequest.FromString,
                    response_serializer=file__gateway__pb2.BrowseDirectoryResponse.SerializeToString,
            ),
            'CreateDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDirectory,
                    request_deserializer=file__gateway__pb2.CreateDirectoryRequest.FromString,
                    response_serializer=file__gateway__pb2.CreateDirectoryResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=file__gateway__pb2.DeleteRequest.FromString,
                    response_serializer=file__gateway__pb2.DeleteResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__gateway__pb2.UploadFileRequest.FromString,
                    response_serializer=file__gateway__pb2.UploadFileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__gateway__pb2.DownloadFileRequest.FromString,
                    response_serializer=file__gateway__pb2.DownloadFileResponse.SerializeToString,
            ),
            'GetFileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileInfo,
                    request_deserializer=file__gateway__pb2.GetFileInfoRequest.FromString,
                    response_serializer=file__gateway__pb2.GetFileInfoResponse.SerializeToString,
            ),
            'InitProjectStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.InitProjectStructure,
                    request_deserializer=file__gateway__pb2.InitProjectStructureRequest.FromString,
                    response_serializer=file__gateway__pb2.InitProjectStructureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_gateway.FileGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('file_gateway.FileGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileGateway(object):
    """Сервис управления файлами и хранилищем
    === Информация о сервере ===
    """

    @staticmethod
    def GetStorageInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_gateway.FileGateway/GetStorageInfo',
            file__gateway__pb2.GetStorageInfoRequest.SerializeToString,
            file__gateway__pb2.GetStorageInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowseDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_gateway.FileGateway/BrowseDirectory',
            file__gateway__pb2.BrowseDirectoryRequest.SerializeToString,
            file__gateway__pb2.BrowseDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_gateway.FileGateway/CreateDirectory',
            file__gateway__pb2.CreateDirectoryRequest.SerializeToString,
            file__gateway__pb2.CreateDirectoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_gateway.FileGateway/Delete',
            file__gateway__pb2.DeleteRequest.SerializeToString,
            file__gateway__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/file_gateway.FileGateway/UploadFile',
            file__gateway__pb2.UploadFileRequest.SerializeToString,
            file__gateway__pb2.UploadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/file_gateway.FileGateway/DownloadFile',
            file__gateway__pb2.DownloadFileRequest.SerializeToString,
            file__gateway__pb2.DownloadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_gateway.FileGateway/GetFileInfo',
            file__gateway__pb2.GetFileInfoRequest.SerializeToString,
            file__gateway__pb2.GetFileInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitProjectStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file_gateway.FileGateway/InitProjectStructure',
            file__gateway__pb2.InitProjectStructureRequest.SerializeToString,
            file__gateway__pb2.InitProjectStructureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
